### ISSUE TITLE
Data files are not following JSONLines format.

### ISSUE THREAD

**Issue by jmbyun** [Dong-JinKim/VTT_object_data#1]
Hi. It seems like your data files are JSON files that represents the array objects, where elements of the arrays are following the schema in  [knowledge-graph-input](https://github.com/uilab-vtt/knowledge-graph-input). 

Please let the files be in JSONLines format where each line of the file represents an object that follows the schema in [knowledge-graph-input](https://github.com/uilab-vtt/knowledge-graph-input).

**Comment by Dong-JinKim** [comment]
This issue has been fixed. Thank you.

**Comment by jmbyun** [comment]
Thank you.
